export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_IS_SING_UP = "AUTH_IS_SING_UP";

export const FETCH_MATCHES = "FETCH_MATCHES";
export const FETCH_MATCHES_FAIL = "FETCH_MATCHES_FAIL";
export const CLEAR_STATE_MATCHES = "CLEAR_STATE_MATCHES";
export const SET_USER_DATA = 'SET_USER_DATA' 
export const MATCHES_LOCATIONS_DATA = 'MATCHES_LOCATIONS_DATA'
export const MATCHES_FILTER_SELECT = "MATCHES_FILTER_SELECT"
export const REMOVE_LIKED_USER = "REMOVE_LIKED_USER"

export const UPDATE_LIKED_USERS = "UPDATE_LIKED_USERS"
export const ADD_LIKED_USER = "ADD_LIKED_USER" 


export const SET_MATCHED_USERS_DATA = "SET_MATCHED_USERS_DATA" 
export const SET_LIKED_USERS_DATA = 'SET_LIKED_USERS_DATA'


export const MESSAGED_USER = "MESSAGED_USER"
export const CLEAR_CHAT_STATE = "CLEAR_CHAT_STATE" 
export const SET_USER_CHAT_DATA = "SET_USER_CHAT_DATA" 
export const SET_MESSAGED_USER_CHAT_DATA = "SET_MESSAGED_USER_CHAT_DATA"
export const FORTMAT_CHAT_DATA = "FORTMAT_CHAT_DATA" 

export const SET_USERS_ADMIN = 'SET_USERS_ADMIN' 